version: '3.1'

services:
  mongo-db:
    image: mongo:latest
    restart: unless-stopped
    container_name: ${MONGO_INITDB_DATABASE}
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    environment:
      - MONGODB_DATABASE="test"
    volumes:
      - ./db_data/:/data/db/
