version: '3.1'

services:
  mongo-db:
    image: mongo
    restart: unless-stopped
    container_name: ${MONGO_INITDB_DATABASE}
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./db_data/:/data/db/
